# Generated by Django 2.0rc1 on 2017-11-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz', models.TextField(blank=True, db_column='PLZ', null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('blockinfo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kraftwerkid', models.TextField(db_column='KraftwerkID')),
                ('blockid', models.TextField(db_column='BlockID', unique=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('blockname', models.TextField(blank=True, null=True)),
                ('initialop', models.IntegerField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('energysource', models.TextField(blank=True, null=True)),
                ('netpower', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blocks',
                'managed': False,
            },
        ),
    ]
