# Generated by Django 2.0rc1 on 2017-11-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plz', models.TextField(blank=True, db_column='PLZ', null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('blockinfo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'addresses',
                'managed': False,
            },
        ),
    ]
