# Generated by Django 2.0.1 on 2018-02-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantmaster', '0002_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantid', models.TextField(unique=True)),
                ('plantname', models.TextField(blank=True, null=True)),
                ('federalstate', models.TextField(blank=True, null=True)),
                ('energysource', models.TextField(blank=True, null=True)),
                ('latestexpanded', models.IntegerField(blank=True, null=True)),
                ('totalpower', models.FloatField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('blockcount', models.IntegerField(blank=True, null=True)),
                ('blockid', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pollutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releases_to', models.TextField(blank=True, null=True)),
                ('pollutant', models.TextField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('potency', models.IntegerField(blank=True, null=True)),
                ('unit_2', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'pollutions',
                'managed': False,
            },
        ),
    ]
