# Generated by Django 3.0.5 on 2020-04-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantmaster', '0003_plants_pollutions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adresses',
        ),
    ]
